[build]
  publish = ".next"
  command = "npm run build"

[functions]
  directory = "netlify/functions"
  included_files = ["netlify/functions/**"]

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200